import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { DownloadInputSchema } from "yt-dlp-bridge";
import { DownloadResultOutputSchema } from "../output-schemas.js";
import { executeDownload } from "../runtime.js";
import { registerTool } from "../tooling.js";

export function registerPostprocessTools(server: McpServer): void {
  const annotations = { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true };

  registerTool(server, "ytdlp_remux", "Download a media URL and remux the resulting video container with ffmpeg, defaulting to MP4 without re-encoding. Use when the user asks to convert containers such as MKV/WebM to MP4.", DownloadInputSchema, (input) => executeDownload({ ...input, postprocess: { ...input.postprocess, remuxVideo: input.postprocess.remuxVideo ?? "mp4" } }), annotations, DownloadResultOutputSchema);
  registerTool(server, "ytdlp_recode", "Download a media URL and re-encode the resulting video with ffmpeg, defaulting to MP4. Use when the user asks for a target video format and accepts re-encoding.", DownloadInputSchema, (input) => executeDownload({ ...input, postprocess: { ...input.postprocess, recodeVideo: input.postprocess.recodeVideo ?? "mp4" } }), annotations, DownloadResultOutputSchema);
  registerTool(server, "ytdlp_extract_audio", "Download a media URL and extract an audio file with ffmpeg/ffprobe. Use when the user asks for MP3, M4A, Opus, WAV, best audio, or audio-only output.", DownloadInputSchema, (input) => executeDownload({ ...input, kind: "audio", postprocess: { ...input.postprocess, extractAudio: true } }), annotations, DownloadResultOutputSchema);
  registerTool(server, "ytdlp_embed_assets", "Download a media URL and embed subtitles, thumbnail, metadata, chapters, or infojson into the output file. Use when the user asks for a self-contained media file with embedded assets.", DownloadInputSchema, (input) => executeDownload({ ...input, postprocess: { ...input.postprocess, embedSubs: input.postprocess.embedSubs ?? true, embedThumbnail: input.postprocess.embedThumbnail ?? true, embedMetadata: input.postprocess.embedMetadata ?? true } }), annotations, DownloadResultOutputSchema);
  registerTool(server, "ytdlp_split_chapters", "Download a media URL and split the result into one file per chapter. Use when the user asks to create separate chapter files or segment a chaptered video.", DownloadInputSchema, (input) => executeDownload({ ...input, postprocess: { ...input.postprocess, splitChapters: true } }), annotations, DownloadResultOutputSchema);
  registerTool(server, "ytdlp_remove_chapters", "Download a media URL and remove chapters matching configured regex filters, defaulting to sponsor-like chapters. Use for chapter removal workflows that need ffmpeg cuts.", DownloadInputSchema, (input) => executeDownload({ ...input, postprocess: { ...input.postprocess, removeChapters: input.postprocess.removeChapters.length ? input.postprocess.removeChapters : [".*sponsor.*"] } }), annotations, DownloadResultOutputSchema);
  registerTool(server, "ytdlp_apply_sponsorblock", "Download a media URL and apply SponsorBlock mark or remove options. Use when the user asks to mark, remove, or chapter SponsorBlock categories during download.", DownloadInputSchema, (input) => executeDownload({ ...input, sponsorblock: { ...input.sponsorblock, mark: input.sponsorblock.mark ?? "default" } }), annotations, DownloadResultOutputSchema);
}
